spring:
  datasource:
    url: jdbc:tc:postgresql:///ufs_pad
    username: postgres
    password: postgres
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: true
