apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ufs-api
  name: ufs-api
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: ufs-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ufs-api
    spec:
      containers:
      - image: bilal0606/ufs-api:2020.1.1
        imagePullPolicy: IfNotPresent
        name: ufs-api
        ports:
          - containerPort: 8800
        env:
          - name: pg_host
            value: postgres-ufs
          - name: pg_port
            value: 5433
          - name: ctms_uri
            value: ctms-api
          - name: ctms_port
            value: 8080
        resources:
          requests:
            #cpu: 200m
            memory: 512Mi
          limits:
            #cpu: 400m
            memory: 1024Mi
        readinessProbe:
          httpGet:
            path: /ufs-api/actuator/info
            port: 8800
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /ufs-api/actuator/info
            port: 8800
          initialDelaySeconds: 180
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ufs-api
  name: ufs-api
  namespace: default
spec:
  ports:
  - nodePort: 30018
    port: 8081
    protocol: TCP
    targetPort: 8800
  selector:
    app: ufs-api
  sessionAffinity: None
  type: LoadBalancer