spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none