# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Feature Build

on:
  push:
    branches-ignore:
      - master
      - main
      - gh-pages
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@1.0.8
    - name: Build with Maven
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B clean install --file pom.xml
      env:
        M2_SECRET_TOKEN: ${{ secrets.M2_SECRET_TOKEN }}
    - name: upload api-spec
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: swaggerDoc
        path: ufs-api/target/swagger.json
        retention-days: 1
  apiSpec:
    name: Release api document
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: download api-spec
      uses: actions/download-artifact@v2
      with:
        name: swaggerDoc
        path: ufs-api/target/swagger.json
    - name: download swagger ui
      run: |
        release_tag=$(curl -sL https://api.github.com/repos/swagger-api/swagger-ui/releases/latest | jq -r ".tag_name")
        curl -sL -o swaggerUi.tar.gz https://api.github.com/repos/swagger-api/swagger-ui/tarball/$release_tag
    - name: extract swagger ui
      uses: brunoborges/justextract@v1
      with:
        file: swaggerUi.tar.gz
    - name: add swagger-doc to swagger ui
      run: |
        mkdir docs
        mv swag*/dist/** docs
        mv docs/index.html .
        mv ufs-api/target/swagger.json docs
        rm -rf swag* *.tar.gz
        sed -i "s|https://petstore.swagger.io/v2/swagger.json|docs/swagger.json/swagger.json|g" index.html
        sed -i "s|href=\"./|href=\"docs/|g" index.html
        sed -i "s|src=\"./|src=\"docs/|g" index.html
    - name: configure git
      run: |
        git config user.name "Github Actions Bot"
        git config user.email "<>"
    - name: publish doc to gh-pages
      run: |
        git push -d origin gh-pages
        git fetch origin
        git checkout -b gh-pages
        git add --all
        git commit -m "Publish API to gh-pages"
        git push --set-upstream origin gh-pages -f